Changes

diff --git a/offlineimap/Maildir/.notmuch/hooks/post-new b/offlineimap/Maildir/.notmuch/hooks/post-new
--- a/offlineimap/Maildir/.notmuch/hooks/post-new
+++ b/offlineimap/Maildir/.notmuch/hooks/post-new
@@ -1,5 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 
-notmuch tag +thread_flagged $(notmuch search --output=threads tag:flagged)
-notmuch tag +muted $(notmuch search --output=threads tag:muted)
-notmuch tag -INBOX $(notmuch search --output=threads tag:muted)
+# TODO: these can fail if there are no results being tagged. `|| true` helps
+# the hook as a whole succeed still, but this is kind of lame.
+
+notmuch tag +thread_flagged $(notmuch search --output=threads tag:flagged) || true
+notmuch tag +muted $(notmuch search --output=threads tag:muted) || true
+notmuch tag -INBOX $(notmuch search --output=threads tag:muted) || true
